baseURL = 'https://blog.nancunchild.cn/'
languageCode = 'zh-cn'
title = 'NanCunChildçš„ç¢ç¢å¿µ'
theme = 'hugo-theme-hello-friend-ng'
pagination.pagerSize = 10
enableEmoji = true

[params]
    dateform        = "Nov 27, 2025"
    dateformShort   = "Nov 27"
    dateformNum     = "2025-11-27"
    dateformNumTime = "2025-11-27 11:04"

    subtitle = "NCCçš„ç¢ç¢å¿µ"
    description = "NanCunChildçš„ä¸ªäººåšå®¢ï¼ŒåŒ…å«ç”Ÿæ´»ï¼ŒæŠ€æœ¯å’Œå¹»æƒ³"
    keywords = "homepage, blog, nancunchild, tech"
    images = ["assets/web_icon.ico"]
    disableReadOtherPosts = false

    enableSharingButtons = true
    enableGlobalLanguageMenu = true

    defaultTheme = "auto"

    [params.author]
        name = "NanCunChild"

    [params.contact]
        email = 'nancunchild@gmail.com'

    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°NCCçš„æ–°åšå®¢ï¼Œè¿™é‡Œæ˜¯NCCçš„ç¢ç¢å¿µ"
    

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        languageCode = 'en-US'
        languageDirection = 'ltr'
        languageName = 'English'
        title = 'English title test'
        weight = 2
        [languages.en.params]
        subtitle = 'English subtitle test'
        [languages.en.params.contact]
            email = 'nancunchild@gmail.com'

    [languages.zh]
        languageCode = 'zh-CN'
        languageDirection = 'ltr'
        languageName = 'Chinese'
        title = 'ä¸­æ–‡æ ‡é¢˜æµ‹è¯•'
        weight = 2
        [languages.zh.params]
        subtitle = 'ä¸­æ–‡å‰¯æ ‡é¢˜æµ‹è¯•'
        [languages.zh.params.contact]
            email = 'nancunchild@gmail.com'

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« "
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "archives"
        name = "å½’æ¡£"
        url = "/archives/"
        weight = 20