baseURL = 'https://blog.nancunchild.cn/'
languageCode = 'zh-CN'
title = 'NanCunChildçš„ç¢ç¢å¿µ'
theme = 'hugo-theme-hello-friend-ng'
pagination.pagerSize = 10
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = false

[params]
    dateform        = "Jan 02, 2006"
    dateformShort   = "Jan 02"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    subtitle = "NCCçš„ç¢ç¢å¿µ"
    description = "NanCunChildçš„ä¸ªäººåšå®¢ï¼ŒåŒ…å«ç”Ÿæ´»ï¼ŒæŠ€æœ¯å’Œå¹»æƒ³"
    keywords = "homepage, blog, nancunchild, tech"
    images = ["assets/web_icon.ico"]
    disableReadOtherPosts = false

    enableSharingButtons = false
    enableGlobalLanguageMenu = true

    defaultTheme = "auto"

    [params.author]
        name = "NanCunChild"

    [params.contact]
        email = 'nancunchild@gmail.com'
    

[languages]
    [languages.zh-cn]
        languageCode = 'zh-CN'
        languageName = 'ä¸­æ–‡'
        weight = 1
        title = 'NanCunChildçš„ç¢ç¢å¿µ'
        [languages.zh-cn.params]
            subtitle = 'ç”Ÿæ´»ã€æŠ€æœ¯ä¸å¹»æƒ³'
            [languages.zh.params.homeInfoParams]
                Title = "ä½ å¥½ ğŸ‘‹"
                Content = "æ¬¢è¿æ¥åˆ°NCCçš„ç¢ç¢å¿µ"

        [[languages.zh-cn.menu.main]]
            identifier = "about"
            name = "å…³äºæˆ‘"
            url = "/about/"
            weight = 5
        [[languages.zh-cn.menu.main]]
            identifier = "posts"
            name = "æ–‡ç« "
            url = "/posts/"
            weight = 10
        [[languages.zh-cn.menu.main]]
            identifier = "archives"
            name = "å½’æ¡£"
            url = "/archives/"
            weight = 20

    [languages.en]
        languageCode = 'en-US'
        languageName = 'English'
        weight = 2
        title = "NanCunChild's Blog"
        [languages.en.params]
            subtitle = 'Tech, Life and Fantasy'
            [languages.en.params.homeInfoParams]
                Title = "Hi there ğŸ‘‹"
                Content = "Welcome to NCC's Blog"

        [[languages.en.menu.main]]
            identifier = "about"
            name = "About"
            url = "/en/about/"
            weight = 5
        [[languages.en.menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/en/posts/"
            weight = 10
        [[languages.en.menu.main]]
            identifier = "archives"
            name = "Archives"
            url = "/en/archives/"
            weight = 20

    [languages.ja]
        languageCode = 'ja-JP'
        languageName = 'æ—¥æœ¬èª'
        weight = 3
        title = 'NanCunChildã®ãƒ–ãƒ­ã‚°'
        [languages.ja.params]
            subtitle = 'ç”Ÿæ´»ã€æŠ€è¡“ã¨ãƒ•ã‚¡ãƒ³ã‚¿ã‚¸ãƒ¼'
            [languages.ja.params.homeInfoParams]
                Title = "ã“ã‚“ã«ã¡ã¯ ğŸ‘‹"
                Content = "NCCã®ãƒ–ãƒ­ã‚°ã¸ã‚ˆã†ã“ã"

        [[languages.ja.menu.main]]
            identifier = "about"
            name = "ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«"
            url = "/ja/about/"
            weight = 5
        [[languages.ja.menu.main]]
            identifier = "posts"
            name = "è¨˜äº‹ä¸€è¦§"
            url = "/ja/posts/"
            weight = 10
        [[languages.ja.menu.main]]
            identifier = "archives"
            name = "ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–"
            url = "/ja/archives/"
            weight = 20