baseURL = 'https://blog.nancunchild.cn/'
languageCode = 'zh-cn'
title = 'NanCunChildçš„ç¢ç¢å¿µ'
theme = 'hugo-theme-hello-friend-ng'
pagination.pagerSize = 10
enableEmoji = true

[params]
    dateform        = "Jan 02, 2006"
    dateformShort   = "Jan 02"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    subtitle = "NCCçš„ç¢ç¢å¿µ"
    description = "NanCunChildçš„ä¸ªäººåšå®¢ï¼ŒåŒ…å«ç”Ÿæ´»ï¼ŒæŠ€æœ¯å’Œå¹»æƒ³"
    keywords = "homepage, blog, nancunchild, tech"
    images = ["assets/web_icon.ico"]
    disableReadOtherPosts = false

    enableSharingButtons = false
    enableGlobalLanguageMenu = true

    defaultTheme = "auto"

    [params.author]
        name = "NanCunChild"

    [params.contact]
        email = 'nancunchild@gmail.com'

    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°NCCçš„æ–°åšå®¢ï¼Œè¿™é‡Œæ˜¯NCCçš„ç¢ç¢å¿µ"
    

[languages]
    [languages.en]
        languageCode = 'en-US'
        languageDirection = 'ltr'
        languageName = 'English'
        title = "There is NanCunChild's Blog"
        weight = 4
        [languages.en.params]
        subtitle = 'English subtitle test'
        [languages.en.params.contact]
            email = 'nancunchild@gmail.com'

    [languages.zh]
        languageCode = 'zh-CN'
        languageDirection = 'ltr'
        languageName = 'Chinese'
        title = 'NanCunChildçš„ç¢ç¢å¿µåšå®¢'
        weight = 4
        [languages.zh.params]
        subtitle = 'è¿™ä¸ªå‰¯æ ‡é¢˜æ˜¯å¹²å˜›çš„'
        [languages.zh.params.contact]
            email = 'nancunchild@gmail.com'

    [languages.ja]
        languageCode = 'ja-JP'
        languageDirection = 'ltr'
        languageName = 'Japanese'
        title = 'NanCunChildã®ãƒ–ãƒ­ã‚°'
        weight = 4
        [languages.ja.params]
        subtitle = 'æ—¥æœ¬èªã®å­—å¹•ãƒ†ã‚¹ãƒˆ'
        [languages.ja.params.contact]
            email = 'nancunchild@gmail.com'

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« "
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "archives"
        name = "å½’æ¡£"
        url = "/archives/"
        weight = 20