baseURL = 'https://blog.nancunchild.cn/'
languageCode = 'zh-cn'
title = 'NanCunChildçš„ç¢ç¢å¿µ'
theme = 'hello-friend-ng'
pagination.pagerSize = 10

[params]
    dateform        = "Jan 02, 2006"
    dateformShort   = "Jan 02"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    subtitle = "NCCçš„ç¢ç¢å¿µ"
    description = "NanCunChildçš„ä¸ªäººåšå®¢ï¼ŒåŒ…å«ç”Ÿæ´»ï¼ŒæŠ€æœ¯å’Œå¹»æƒ³"
    keywords = "homepage, blog, nancunchild, tech"
    images = ["assets/web_icon.ico"]
    disableReadOtherPosts = false

    enableSharingButtons = false
    enableGlobalLanguageMenu = true
    defaultContentLanguage = 'zh'
    defaultContentLanguageInSubdir = false

    defaultTheme = "auto"

    [params.author]
        name = "NanCunChild"

    [params.contact]
        email = 'nancunchild@gmail.com'

    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°NCCçš„æ–°åšå®¢ï¼Œè¿™é‡Œæ˜¯NCCçš„ç¢ç¢å¿µ"
    

[languages]
    [languages.zh]
        languageCode = 'zh-CN'
        languageName = 'ä¸­æ–‡'
        weight = 1
        title = 'NanCunChildçš„ç¢ç¢å¿µ'
        [languages.zh.params]
            subtitle = 'ç”Ÿæ´»ã€æŠ€æœ¯ä¸å¹»æƒ³'
        [[languages.zh.menu.main]]
            identifier = "about"
            name = "å…³äºæˆ‘"
            url = "/about/"
            weight = 5
        [[languages.zh.menu.main]]
            identifier = "posts"
            name = "æ–‡ç« "
            url = "/posts/"
            weight = 10
        [[languages.zh.menu.main]]
            identifier = "archives"
            name = "å½’æ¡£"
            url = "/archives/"
            weight = 20

    [languages.en]
        languageCode = 'en-US'
        languageName = 'English'
        weight = 2
        title = "NanCunChild's Blog"
        [languages.en.params]
            subtitle = 'Tech, Life and Fantasy'
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About"
            url = "/about/"
            weight = 5
        [[languages.en.menu.main]]
            identifier = "posts"
            name = "Posts"
            url = "/posts/"
            weight = 10
        [[languages.en.menu.main]]
            identifier = "archives"
            name = "Archives"
            url = "/archives/"
            weight = 20

    [languages.ja]
        languageCode = 'ja-JP'
        languageName = 'æ—¥æœ¬èª'
        weight = 3
        title = 'NanCunChildã®ãƒ–ãƒ­ã‚°'
        [languages.ja.params]
            subtitle = 'ç”Ÿæ´»ã€æŠ€è¡“ã¨ãƒ•ã‚¡ãƒ³ã‚¿ã‚¸ãƒ¼'
        [[languages.ja.menu.main]]
            identifier = "about"
            name = "ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«"
            url = "/about/"
            weight = 5
        [[languages.ja.menu.main]]
            identifier = "posts"
            name = "è¨˜äº‹ä¸€è¦§"
            url = "/posts/"
            weight = 10
        [[languages.ja.menu.main]]
            identifier = "archives"
            name = "ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–"
            url = "/archives/"
            weight = 20