baseURL = 'https://blog.nancunchild.cn/'
languageCode = 'zh-cn'
title = 'NCC Blog on Hugo'
theme = 'hugo-theme-hello-friend-ng'

enableEmoji = true

[params]
    description = "è¿™æ˜¯æˆ‘çš„ä¸ªäººåšå®¢"
    [params.author]
        name = "NanCunChild"
        email = "nancunchild@gmail.com"
    defaultTheme = "auto"

    [params.homeInfoParams]
        Title = "Hi there ğŸ‘‹"
        Content = "æ¬¢è¿æ¥åˆ°NCCçš„æ–°åšå®¢ï¼Œè¿™é‡Œæ˜¯NCCçš„ç¢ç¢å¿µ"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "æ–‡ç« "
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "archives"
        name = "å½’æ¡£"
        url = "/archives/"
        weight = 20